//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSY.Infra.CrossCutting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSY.Infra.CrossCutting.Common.Resources.UIConfig", typeof(UIConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aceitar.
        /// </summary>
        public static string aceitar {
            get {
                return ResourceManager.GetString("aceitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Amigo.
        /// </summary>
        public static string AdicionarAmigo {
            get {
                return ResourceManager.GetString("AdicionarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora.
        /// </summary>
        public static string Agora {
            get {
                return ResourceManager.GetString("Agora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string Amigos {
            get {
                return ResourceManager.GetString("Amigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos Pendentes.
        /// </summary>
        public static string AmigosPendentes {
            get {
                return ResourceManager.GetString("AmigosPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anterior.
        /// </summary>
        public static string anterior {
            get {
                return ResourceManager.GetString("anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear postagens desse perfil.
        /// </summary>
        public static string BloquearPostagensDessePerfil {
            get {
                return ResourceManager.GetString("BloquearPostagensDessePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidades.
        /// </summary>
        public static string Comunidades {
            get {
                return ResourceManager.GetString("Comunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Configuracoes {
            get {
                return ResourceManager.GetString("Configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depoimentos.
        /// </summary>
        public static string Depoimentos {
            get {
                return ResourceManager.GetString("Depoimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dia atrás.
        /// </summary>
        public static string diaatras {
            get {
                return ResourceManager.GetString("diaatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dias atrás.
        /// </summary>
        public static string diasatras {
            get {
                return ResourceManager.GetString("diasatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Perfil.
        /// </summary>
        public static string EditarPerfil {
            get {
                return ResourceManager.GetString("EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando.
        /// </summary>
        public static string Esperando {
            get {
                return ResourceManager.GetString("Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir comentário.
        /// </summary>
        public static string ExcluirComentário {
            get {
                return ResourceManager.GetString("ExcluirComentário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir postagem.
        /// </summary>
        public static string ExcluirPostagem {
            get {
                return ResourceManager.GetString("ExcluirPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir postagens selecionadas.
        /// </summary>
        public static string ExcluirPostagensSelecionadas {
            get {
                return ResourceManager.GetString("ExcluirPostagensSelecionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir recado.
        /// </summary>
        public static string Excluirrecado {
            get {
                return ResourceManager.GetString("Excluirrecado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir recados selecionados.
        /// </summary>
        public static string ExcluirRecadosSelecionados {
            get {
                return ResourceManager.GetString("ExcluirRecadosSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hora atrás.
        /// </summary>
        public static string horaatras {
            get {
                return ResourceManager.GetString("horaatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas atrás.
        /// </summary>
        public static string horasatras {
            get {
                return ResourceManager.GetString("horasatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Depoimentos.
        /// </summary>
        public static string MeusDepoimentos {
            get {
                return ResourceManager.GetString("MeusDepoimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Recados.
        /// </summary>
        public static string MeusRecados {
            get {
                return ResourceManager.GetString("MeusRecados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuto atrás.
        /// </summary>
        public static string minutoatras {
            get {
                return ResourceManager.GetString("minutoatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos atrás.
        /// </summary>
        public static string minutosatras {
            get {
                return ResourceManager.GetString("minutosatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar postagem.
        /// </summary>
        public static string OcultarPostagem {
            get {
                return ResourceManager.GetString("OcultarPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string Pagina {
            get {
                return ResourceManager.GetString("Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas.
        /// </summary>
        public static string Pessoas {
            get {
                return ResourceManager.GetString("Pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primeiro.
        /// </summary>
        public static string primeiro {
            get {
                return ResourceManager.GetString("primeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to próximo.
        /// </summary>
        public static string proximo {
            get {
                return ResourceManager.GetString("proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recados.
        /// </summary>
        public static string Recados {
            get {
                return ResourceManager.GetString("Recados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Amigo.
        /// </summary>
        public static string RemoverAmigo {
            get {
                return ResourceManager.GetString("RemoverAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundo atrás.
        /// </summary>
        public static string segundoatras {
            get {
                return ResourceManager.GetString("segundoatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos atrás.
        /// </summary>
        public static string segundosatras {
            get {
                return ResourceManager.GetString("segundosatras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as atualizações.
        /// </summary>
        public static string TodasAsAtualizacoes {
            get {
                return ResourceManager.GetString("TodasAsAtualizacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to último.
        /// </summary>
        public static string ultimo {
            get {
                return ResourceManager.GetString("ultimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver mais comentários.
        /// </summary>
        public static string VerMaisComentarios {
            get {
                return ResourceManager.GetString("VerMaisComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver menos comentários.
        /// </summary>
        public static string VerMenosComentarios {
            get {
                return ResourceManager.GetString("VerMenosComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitantes do perfil.
        /// </summary>
        public static string Visitantesdoperfil {
            get {
                return ResourceManager.GetString("Visitantesdoperfil", resourceCulture);
            }
        }
    }
}
